[formatting]
column_width = 100
indent_string = "    "
reorder_keys = false
array_trailing_comma = false
array_auto_expand = true
array_auto_expand_max = 4
array_auto_collapse = false
allowed_blank_lines = 1
